#EXTM3U
#EXTINF:-1,SEÑAL PERU TV
https://livestream.perucast.com/hls/stream.m3u8
#EXTINF:-1,LATINA
https://jireh-4-hls-video-us-isp.dps.live/hls-video/567ffde3fa319fadf3419efda25619456231dfea/latina/latina.smil/latina/livestream2/playlist.m3u8
#EXTINF:-1,ATV
https://alba-pe-atv-atv.stream.mediatiquestream.com/original.m3u8
#EXTINF:-1,RPP TV (1080p)
https://cdn-ssai.smartbit.co/rpp/index.m3u8
#EXTINF:-1,Exitosa TV (720p)
https://luna-4-video.mediaserver.digital/exitosatv_233b-4b49-a726-5a451262/index.m3u8
#EXTINF:-1,ANIMAKIDS
https://live-evg8.tv360.bitel.com.pe/bitel/animakids/playlist.m3u8?uid=6772419
#EXTINF:-1,CNCITY
https://envivo.cncity.live/hls/envivo.m3u8
#EXTINF:-1,GOKU TV 					
https://live20.bozztv.com/giatv/giatv-dball/dball/playlist.m3u8
#EXTINF:-1,TELEVISA
https://televisa-televisa-1-it.samsung.wurl.tv/playlist.m3u8
#EXTINF:-1,RCN COLOMBIA
http://astra.fibernetisp.com.co/play/a0b5/index.m3u8
#EXTINF:-1,TDP
https://ssai.aniview.com/api/v1/hls/stream.m3u8?cb=[CACHEBUSTER&AV_WIDTH=[ADS.W]&AV_HEIGHT=[ADS.H]&AV_APPNAME=[ADS.APP_NAME]&AV_APPSTOREURL=[ADS.APP_STORE_URL]&AV_APPPKGNAME=[ADS.APP_BUNDLE]&AV_IDFA=[ADS.IFA]&AV_IFA_TYPE=[ADS.IFA_TYPE]&AV_CCPA=[ADS.US_PRIVACY]&AV_GDPR=[ADS.GDPR]&AV_CONSENT=[ADS.GDPR_CONSENT]&AV_CONTENT_URL=&AV_CONTENT_TITLE=&AV_CONTENT_EPISODE=&AV_CONTENT_SERIES=&AV_CONTENT_SEASON=&AV_CONTENT_KEYWORDS=&AV_CONTENT_NETWORK=&AV_CONTENT_ID=[ADS.VIDAA_ADS_CONTENTID]&AV_CONTENT_CHANNEL=&AV_CONTENT_CONTEXT=&AV_CONTENT_LENGTH=&AV_VAUTH=[ADS.VAUTH]&AV_DNT=[ADS.DNT]&Content_Id=[ADS.ADS_CONTENTID]&AV_LANGUAGE=[ADS.DEVICE_LANGUAGE]&AV_RTB_DEVICE_TYPE=[ADS.DEVICE_TYPE]&AV_OSVERS=[ADS.DEVICE_OSV]&AVS_SSAIID=6835a4ac56e24897ca0a5b8d&AV_CONTENT_LANGUAGE=sp&AV_CONTENT_GENRE=sport&AV_CONTENT_CAT=IAB17&AV_CONTENT_RATING=16&AV_CLIENT_SECTION=RTVE_tdp&content_channel_name=TDP&content_livestream=1&AV_CONTENT_PROVIDER=RTVE&ads.vidaa_ads_param=1190602996]
#EXTINF:-1,CAZETV BRASIL
https://dfr80qz435crc.cloudfront.net/MNOP/Amagi/Caze/Caze_TV_BR/1080p-vtt/index.m3u8
#EXTINF:-1,TELEMUNDO DEPORTES AHORA
https://d1rqgw5gocwo9i.cloudfront.net/10009/99951459/hls/master.m3u8?ads.xumo_channelId=99951459&ads.asnw=169843&ads.afid=442535792&ads.sfid=23780352&ads.caid=telemundodeportesahora_linear&ads.csid=xumo_
#EXTINF:-1,AZTECA DEPORTE
http://astra.fibernetisp.com.co/play/a0tj/index.m3u8
#EXTINF:-1,TUDN (Champions)
https://streaming.alwaysdata.net/tudn.php
#EXTINF:-1,DSPORTS
https://tinyurl.com/dsportsgo
#EXTINF:-1,DSPORTS 2
https://tinyurl.com/dsportsgo2
#EXTINF:-1,SPORTV
https://tinyurl.com/sportvbra
#EXTINF:-1,TUDN
https://tinyurl.com/tudnsports
#EXTINF:-1,TyC SPORTS
https://tinyurl.com/tycsportsar
#EXTINF:-1,KARIBEÑA TV
https://luna-1-video.mediaserver.digital/karibenatv_685a-pe-a5676-584412/video.m3u8
#EXTINF:-1,NOW 90S00S
https://amg01076-amg01076c19-lg-es-10331.playouts.now.amagi.tv/ts-eu-w1-n2/playlist/amg01076-lightning-now90s00s-lges/playlist.m3u8
#EXTINF:-1,24hrKpop
https://live.24hrkpop.com/hls/stream.m3u8
#EXTINF:-1,XITE_Siempre_Latino_(1080p)https://d1xc25jm9e0l4b.cloudfront.net/XITE_Siempre_Latino.m3u8
#EXTINF:-1,Memorias Corazón HD
https://video.xtrematv.com:3401/live/grupomemoriaslive.m3u8
